#CREATE DATABASE `curs13`;

CREATE TABLE tasks (
	id  INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	title VARCHAR(255) NOT NULL,
	start_date DATE,
	due_date DATE,
	`status` TINYINT NOT NULL,
	DESCRIPTION TEXT,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=INNODB;

CREATE TABLE checklists (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	task_id INT NOT NULL,
	todo VARCHAR(255) NOT NULL,
	FOREIGN KEY(task_id)
		REFERENCES tasks (id)
		ON UPDATE RESTRICT ON DELETE CASCADE 
		);
		
CREATE TABLE roles (
	id INT AUTO_INCREMENT PRIMARY KEY,
	todo VARCHAR(50) NOT NULL,
	DESCRIPTION TEXT
);

CREATE TABLE users (
	id INT AUTO_INCREMENT PRIMARY KEY,
	username VARCHAR(50) NOT NULL UNIQUE,
	email VARCHAR(100) NOT NULL UNIQUE,
	first_name VARCHAR(50) NOT NULL,
	last_name VARCHAR(50) NOT NULL,
	country VARCHAR(50),
	adress VARCHAR(255),
	occupation VARCHAR(100),
	birth_date DATE,
	account_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	gender ENUM('Male', 'Female') NOT NULL,
	PASSWORD VARCHAR(255) NOT NULL
);

CREATE TABLE authentications (
	id INT AUTO_INCREMENT PRIMARY KEY,
	user_id INT NOT NULL,
	login_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	browser VARCHAR(100),
	ip_address VARCHAR(50),
	success BOOLEAN NOT NULL,
	FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE users_roles (
	id INT AUTO_INCREMENT PRIMARY KEY,
	user_id INT NOT NULL,
	role_id INT NOT NULL,
	FOREIGN KEY (user_id) REFERENCES users(id),
	FOREIGN KEY (role_id) REFERENCES roles(id)
);
